using System.Globalization;
using System.Text.Json;
using DotnetRelease;
using DotnetRelease.Graph;
using DotnetRelease.Summary;
using JsonSchemaInjector;

namespace VersionIndex;

/// <summary>
/// Generates SDK index files (sdk/index.json) for each major version.
/// The sdk/index.json provides feature band metadata and links to downloads.
/// Actual download files are generated by DownloadsIndexFiles in the downloads/ directory.
/// </summary>
public class SdkIndexFiles
{
    /// <summary>
    /// Generates SDK index files for all major versions that support SDK feature bands (8.0+)
    /// </summary>
    public static async Task GenerateAsync(List<MajorReleaseSummary> summaries, string rootDir)
    {
        if (!Directory.Exists(rootDir))
        {
            throw new DirectoryNotFoundException($"Root directory does not exist: {rootDir}");
        }

        var numericStringComparer = StringComparer.Create(CultureInfo.InvariantCulture, CompareOptions.NumericOrdering);

        foreach (var summary in summaries)
        {
            // Only generate SDK indexes for .NET 8.0 and later as per specification
            if (!IsVersionSupported(summary.MajorVersion))
            {
                continue;
            }

            var majorVersionDir = Path.Combine(rootDir, summary.MajorVersion);
            if (!Directory.Exists(majorVersionDir))
            {
                continue;
            }

            Console.WriteLine($"Generating SDK index for .NET {summary.MajorVersion}");

            var sdkDir = Path.Combine(majorVersionDir, FileNames.Directories.Sdk);
            Directory.CreateDirectory(sdkDir);

            await GenerateSdkIndex(summary, sdkDir, rootDir, numericStringComparer);
        }
    }

    private static bool IsVersionSupported(string version)
    {
        // SDK hive is only supported for .NET 8.0 and later
        if (string.IsNullOrEmpty(version) || !version.Contains('.'))
        {
            return false;
        }

        var parts = version.Split('.');
        if (parts.Length < 2 || !int.TryParse(parts[0], out var major))
        {
            return false;
        }

        return major >= 8;
    }

    private static async Task GenerateSdkIndex(
        MajorReleaseSummary summary,
        string sdkDir,
        string rootDir,
        StringComparer numericStringComparer)
    {
        var indexPath = Path.Combine(sdkDir, FileNames.Index);
        var indexRelativePath = $"{summary.MajorVersion}/{FileNames.Directories.Sdk}/{FileNames.Index}";

        // Determine latest SDK versions across all feature bands
        var allSdkVersions = summary.SdkBands
            .SelectMany(b => summary.PatchReleases
                .SelectMany(p => p.Components
                    .Where(c => c.Name.Equals("sdk", StringComparison.OrdinalIgnoreCase) &&
                               c.Version.StartsWith(b.Version[..5]))
                    .Select(c => (Component: c, PatchRelease: p))))
            .OrderByDescending(x => x.Component.Version, numericStringComparer)
            .ToList();

        var latestSdk = allSdkVersions.FirstOrDefault().Component?.Version;
        var latestSecuritySdk = allSdkVersions
            .FirstOrDefault(x => x.PatchRelease.Security)
            .Component?.Version;

        // Determine the latest feature band (the one containing the latest SDK)
        var latestFeatureBand = summary.SdkBands
            .OrderByDescending(b => b.Version, numericStringComparer)
            .FirstOrDefault(b => b.SupportPhase == SupportPhase.Active);
        var latestFeatureBandVersion = latestFeatureBand != null
            ? latestFeatureBand.Version[..5] + "xx"
            : null;

        // Create main links - self link has no title (inferable)
        var links = new Dictionary<string, HalLink>
        {
            [HalTerms.Self] = new HalLink($"{Location.GitHubBaseUri}{indexRelativePath}"),
            [LinkRelations.ReleaseMajor] = new HalLink($"{Location.GitHubBaseUri}{summary.MajorVersion}/{FileNames.Index}")
            {
                Title = LinkTitles.MajorVersionIndex,
            },
            ["downloads"] = new HalLink($"{Location.GitHubBaseUri}{summary.MajorVersion}/{FileNames.Directories.Downloads}/{FileNames.Index}")
            {
                Title = LinkTitles.DownloadsIndex,
            }
        };

        // Create feature band entries (sorted by version descending)
        var featureBandEntries = summary.SdkBands
            .OrderByDescending(b => b.Version, numericStringComparer)
            .Select(sdkBand =>
            {
                var bandVersion = sdkBand.Version[..5] + "xx"; // e.g., "8.0.4xx"

                // Find the latest SDK version in this feature band
                var latestInBand = summary.PatchReleases
                    .SelectMany(p => p.Components
                        .Where(c => c.Name.Equals("sdk", StringComparison.OrdinalIgnoreCase) &&
                                   c.Version.StartsWith(sdkBand.Version[..5]))
                        .Select(c => (Component: c, PatchRelease: p)))
                    .OrderByDescending(x => x.Component.Version, numericStringComparer)
                    .FirstOrDefault();

                var latestSdkInBand = latestInBand.Component?.Version;
                var latestPatchRelease = latestInBand.PatchRelease;

                // Build links for this feature band
                // Note: No titles or types in _embedded links - context established by parent
                var bandLinks = new Dictionary<string, HalLink>
                {
                    ["downloads"] = new HalLink($"{Location.GitHubBaseUri}{summary.MajorVersion}/{FileNames.Directories.Downloads}/sdk-{bandVersion}.json")
                };

                // Add release-patch link (to the patch release this SDK is part of)
                if (latestPatchRelease?.PatchDirPath != null)
                {
                    var patchIndexPath = $"{latestPatchRelease.PatchDirPath}/{FileNames.Index}";
                    bandLinks["release-patch"] = new HalLink($"{Location.GitHubBaseUri}{patchIndexPath}");
                }

                // Add release-month link
                if (latestPatchRelease != null)
                {
                    var year = latestPatchRelease.ReleaseDate.Year.ToString("D4");
                    var month = latestPatchRelease.ReleaseDate.Month.ToString("D2");
                    var monthIndexPath = $"{FileNames.Directories.Timeline}/{year}/{month}/{FileNames.Index}";
                    bandLinks["release-month"] = new HalLink($"{Location.GitHubBaseUri}{monthIndexPath}");
                }

                return new SdkFeatureBandEntry(
                    latestSdkInBand ?? bandVersion,  // version (latest SDK in band)
                    bandVersion,                      // band (e.g., "9.0.3xx")
                    latestPatchRelease != null
                        ? new DateTimeOffset(latestPatchRelease.ReleaseDate.ToDateTime(TimeOnly.MinValue), TimeSpan.FromHours(-8))
                        : null,
                    $".NET SDK {bandVersion}",
                    sdkBand.SupportPhase,
                    HalHelpers.OrderLinks(bandLinks));
            })
            .ToList();

        // Create the SDK index (feature bands only, no historical releases)
        var sdkIndex = new SdkVersionIndex(
            ReleaseKind.SdkIndex,
            summary.MajorVersion,
            $".NET SDK {summary.MajorVersion}")
        {
            Latest = latestSdk,
            LatestSecurity = latestSecuritySdk,
            LatestFeatureBand = latestFeatureBandVersion,
            Links = HalHelpers.OrderLinks(links),
            Embedded = new SdkVersionIndexEmbedded(featureBandEntries)
        };

        // Serialize to JSON
        var json = JsonSerializer.Serialize(
            sdkIndex,
            SdkVersionIndexSerializerContext.Default.SdkVersionIndex);

        // Add schema reference
        var schemaUri = $"{Location.GitHubBaseUri}{FileNames.Directories.Schemas}/{FileNames.Schemas.SdkVersionIndex}";
        var jsonWithSchema = JsonSchemaInjector.JsonSchemaInjector.AddSchemaToContent(json, schemaUri);

        await File.WriteAllTextAsync(indexPath, (jsonWithSchema ?? json) + '\n');
    }
}
